// service-worker.js



const cacheName = 'game-cache-v1';
const cacheFiles = [
'/',
'index.html',
'package.json',
'/js/plugins/WeaponSkill.js',
'/js/plugins/TitleCommandPosition.js',
'/js/plugins/SimpleMsgSideView.js',
'/js/plugins/MadeWithMv.js',
'/js/plugins/ItemBook.js',
'/js/plugins/EnemyBook.js',
'/js/plugins/Community_Basic.js',
'/js/plugins/AltSaveScreen.js',
'/js/plugins/AltMenuScreen.js',
'/js/libs/pixi.js',
'/js/libs/pixi-tilemap.js',
'/js/libs/pixi-picture.js',
'/js/libs/lz-string.js',
'/js/libs/iphone-inline-video.browser.js',
'/js/libs/fpsmeter.js',
'/js/rpg_windows.js',
'/js/rpg_sprites.js',
'/js/rpg_scenes.js',
'/js/rpg_objects.js',
'/js/rpg_managers.js',
'/js/rpg_core.js',
'/js/main.js',
'/fonts/mplus-1m-regular.ttf',
'/fonts/gamefont.css',
'/data/Weapons.json',
'/data/Troops.json',
'/data/Tilesets.json',
'/data/System.json',
'/data/States.json',
'/data/Skills.json',
'/data/MapInfos.json',
'/data/Map006.json',
'/data/Map005.json',
'/data/Map004.json',
'/data/Map003.json',
'/data/Map002.json',
'/data/Map001.json',
'/data/Items.json',
'/data/Enemies.json',
'/data/CommonEvents.json',
'/data/Classes.json',
'/data/Armors.json',
'/data/Animations.json',
'/data/Actors.json',
'/audio/se/Thunder6.ogg',
'/audio/se/Thunder6.m4a',
'/audio/se/Thunder5.ogg',
'/audio/se/Thunder5.m4a',
'/audio/se/Thunder1.ogg',
'/audio/se/Thunder1.m4a',
'/audio/se/Sword5.ogg',
'/audio/se/Sword5.m4a',
'/audio/se/Starlight.ogg',
'/audio/se/Starlight.m4a',
'/audio/se/Slash1.ogg',
'/audio/se/Slash1.m4a',
'/audio/se/Skill1.ogg',
'/audio/se/Skill1.m4a',
'/audio/se/Shop1.ogg',
'/audio/se/Shop1.m4a',
'/audio/se/Save.ogg',
'/audio/se/Save.m4a',
'/audio/se/Saint2.ogg',
'/audio/se/Saint2.m4a',
'/audio/se/Run.ogg',
'/audio/se/Run.m4a',
'/audio/se/Reflection.ogg',
'/audio/se/Reflection.m4a',
'/audio/se/Recovery.ogg',
'/audio/se/Recovery.m4a',
'/audio/se/Paralyze1.ogg',
'/audio/se/Paralyze1.m4a',
'/audio/se/Open1.ogg',
'/audio/se/Open1.m4a',
'/audio/se/Move1.ogg',
'/audio/se/Move1.m4a',
'/audio/se/Miss.ogg',
'/audio/se/Miss.m4a',
'/audio/se/Magic1.ogg',
'/audio/se/Magic1.m4a',
'/audio/se/Load.ogg',
'/audio/se/Load.m4a',
'/audio/se/Item3.ogg',
'/audio/se/Item3.m4a',
'/audio/se/Ice5.ogg',
'/audio/se/Ice5.m4a',
'/audio/se/Ice1.ogg',
'/audio/se/Heal3.ogg',
'/audio/se/Heal3.m4a',
'/audio/se/Fire3.ogg',
'/audio/se/Fire3.m4a',
'/audio/se/Evasion2.ogg',
'/audio/se/Evasion2.m4a',
'/audio/se/Evasion1.ogg',
'/audio/se/Evasion1.m4a',
'/audio/se/Equip1.ogg',
'/audio/se/Equip1.m4a',
'/audio/se/Decision1.ogg',
'/audio/se/Decision1.m4a',
'/audio/se/Damage5.ogg',
'/audio/se/Damage5.m4a',
'/audio/se/Damage4.ogg',
'/audio/se/Damage4.m4a',
'/audio/se/Cursor2.ogg',
'/audio/se/Cursor2.m4a',
'/audio/se/Collapse4.ogg',
'/audio/se/Collapse4.m4a',
'/audio/se/Collapse3.ogg',
'/audio/se/Collapse3.m4a',
'/audio/se/Collapse2.ogg',
'/audio/se/Collapse2.m4a',
'/audio/se/Collapse1.ogg',
'/audio/se/Collapse1.m4a',
'/audio/se/Chest1.ogg',
'/audio/se/Chest1.m4a',
'/audio/se/Cancel2.ogg',
'/audio/se/Cancel2.m4a',
'/audio/se/Buzzer1.ogg',
'/audio/se/Buzzer1.m4a',
'/audio/se/Blow3.ogg',
'/audio/se/Blow3.m4a',
'/audio/se/Battle1.ogg',
'/audio/se/Battle1.m4a',
'/audio/me/Victory1.ogg',
'/audio/me/Victory1.m4a',
'/audio/me/Gameover1.ogg',
'/audio/me/Gameover1.m4a',
'/audio/me/Defeat1.ogg',
'/audio/me/Defeat1.m4a',
'/audio/bgm/Theme6.ogg',
'/audio/bgm/Theme6.m4a',
'/audio/bgm/Ship3.ogg',
'/audio/bgm/Ship3.m4a',
'/audio/bgm/Ship2.ogg',
'/audio/bgm/Ship2.m4a',
'/audio/bgm/Ship1.ogg',
'/audio/bgm/Ship1.m4a',
'/audio/bgm/Battle1.ogg',
'/audio/bgm/Battle1.m4a'
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(cacheName)
      .then((cache) => {
        return cache.addAll(cacheFiles);
      })
  );
});

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request)
      .then((response) => {
        if (response) {
          return response;
        }

        return fetch(event.request);
      })
  );
});
